import Head from 'next/head'
import Layout from '../components/Layout'
import Hero from '../components/Hero'
import styles from '../styles/Home.module.css'
import Services from '../components/Services'



export default function Home() {
  return (
  <Layout>
    <div className={styles.container}>
      <Head>
        <title>11</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/neon3.avif" />
      </Head>

      <main>
        <Hero/>
        <Services/>
      </main>


    </div>
  </Layout> 
  )
}
