import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>11</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/neon3.avif" />
      </Head>

      <main>
        <h1>Fresh Pizza every Wednesday</h1>
      </main>


    </div>
  )
}
